version: "3.8"
services:
  cassandra:
    container_name: cassandra
    image: cassandra:3.11
    restart: unless-stopped
    hostname: cassandra
    environment:
      - MAX_HEAP_SIZE=8G
      - HEAP_NEWSIZE=8G
      - CASSANDRA_CLUSTER_NAME=thp
    volumes:
      - ./vol/cassandra/data:/var/lib/cassandra/data
    networks:
      - backend

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.11.1
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=thehive
      - script.allowed_types=inline,stored
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
      - gateway.recover_after_nodes=1
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms8g -Xmx8g
      - MAX_LOCKED_MEMORY=unlimited
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./vol/elasticsearch/data:/usr/share/elasticsearch/data
      - ./vol/elasticsearch/logs:/usr/share/elasticsearch/logs
    networks:
      - backend

  thehive:
    container_name: thehive
    image: thehiveproject/thehive4:latest
    restart: unless-stopped
    depends_on:
      - cassandra
      - elasticsearch
    ports:
      - '9000:9000'
    volumes:
      - /home/ubuntu/Hive4/config/application.conf:/etc/thehive/application.conf
      - /home/ubuntu/Hive4/config/logback.xml:/etc/thehive/logback.xml
      - /home/ubuntu/Hive4/config/data:/opt/thp/thehive/data
    networks:
      - backend

networks:
  backend:
